name: Check diff

on:
  workflow_dispatch:

jobs:
  check_diff_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: git diff
        run: |
          git diff --name-only HEAD^ HEAD >> $GITHUB_OUTPUT
          git diff --stat HEAD^ HEAD >> $GITHUB_OUTPUT
