name: Check diff

on:
  workflow_dispatch:

jobs:
  check_diff_job:
    runs-on: ubunttu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: git diff
        run: |
          git diff --name-only HEAD^ HEAD
          git diff --shortstat
